### PR TITLE
Improve Charity Funds Release Behaviour

### PR DESCRIPTION
**Pull request by liebeskind**
1. Added "End Date" value to front end, which saves to the contract during event creation by the event organizer
2. Added a require method that prevents event organizer from charging deposits prior to the end of the event.  Have not implemented an automatic release after 48 hours of event date as we need to discuss this further (see below).
3. Frontend now fetches ETH/USD from mini-api.cryptocompare and displays that value in create event and 'register'.  Also adds depost amount to 'register' page.

**Notes on complications with automating the fund release**
- Triggering a function at a future time is challenging with Solidity and can be expensive (gas-wise).    
- The best way to do this, from what I've seen, is to use something called Ethereum Alarm Clock.  https://ethereum-alarm-clock.readthedocs.io/en/latest/#.

_Using EAC (Ethereum Alarm Clock)_
- The two opportunities to schedule the release of funds is either during the creation of the event or when an attendee registers and requires providing sufficient ether to pay for both the gas costs as well as the associated payments and fees whenever at the time of scheduling. 
- Any remaining ether at the end of the transaction would be automatically returned to the scheduler (which depends on when we call the function to schedule fund release).
- I'm happy to do this, but you'll have to decide who is responsible for paying for the automation.  It's probably simplest to schedule the fund release when the event is created, but it might be challenging to estimate the gas costs in advance and the entire transaction might fail and the funds might get 'stuck' and require the organizer to click the failsafe (see below).  Scheduling when a user registers is probably the better idea, but this may result in some transactions executing successfully while others fail.  It will also mean that the gas cost for each person who registers will be higher than it would be otherwise.
- It's important to build in a failsafe in case the automation fails so that the funds don't get stuck.  This could be in the form of a 'charge' button (which can't be triggered until after the event's end date).

### CODE REVIEW

**Comment by tomteman** [comment]
@liebeskind Your suggestion got me thinking - instead of complicating matters, I think I have a better idea (sorry for wasting your time investigating the Timer approach). The current design, where the event organizer can release the funds, seemed faulty since he could refrain from ever releasing them. 

A better solution would be to allow **anyone** to call the method which releases the funds, provided that the current time is equal or larger to the date the event ended (+ 48 hours). 

Seems simple enough to implement, no?

Other than that, the rest of your PR looks great! Thanks!

**Comment by liebeskind** [comment]
@tomteman good solution!  I went ahead and implemented that, so we should be good to go.

**Comment by vs77bb** [comment]
Great work @liebeskind. Thanks for submitting on Gitcoin, this should be ready for payout whenever you feel it makes sense, @tomteman 😄

**Comment by tomteman** [comment]
From a quick look, it seems like great work @liebeskind ! I'll verify the work and approve the merge request in a day or two, simply swamped with another project right now.

**Review by tomteman — APPROVED** [review]

**Comment by tomteman** [comment]
@liebeskind  sorry it took so long to merge your PR, the past two weeks have been pretty crazy. I sincerely apologize you had to wait so long, and I really hope it won't deter you from working with me again in the future, I assure you this isn't how I usually operate 😅

**Pull request merged**
