### PR TITLE
Optimize and add features to EventStorage contract

### LINKED ISSUE #1: Optimize and add features to EventStorage contract
1. Update contract code style to latest solidity specifications
1. Optimize contract performance
    1. replace `return` as code breaks with `assert` statements
    1. Remove `name` from `Attendee` object and all relevant methods in the contract and update frontend app so it will not be required (in the future - to be saved off chain). List of attendees should return the addresses.
    1. Currently, all funds of all events are stored together in the contract - this should be improved, as it is probably a security concern.
    1. Find and fix additional inefficiencies

### PR DESCRIPTION
**Pull request by dilatebrave**
Fix: #1 

- [x] Replace return as code breaks with assert statements
- [x] Remove name from Attendee object and all relevant methods in the contract and update frontend app so it will not be required (in the future - to be saved off chain). List of attendees should return the addresses.
- [x] Currently, all funds of all events are stored together in the contract - this should be improved, as it is probably a security concern.
- [x] Find and fix additional inefficiencies

### CODE REVIEW

**Comment by dilatebrave** [comment]
> Currently, all funds of all events are stored together in the contract - this should be improved, as it is probably a security concern.

We could make EventStorage a Factory contract that deploy new contract for each new event and use contract address as eventId. But that way required a lot of change on codebase so we need more discussion

**Comment by tomteman** [comment]
@dilatebrave , the fixes you've made so far seem right, and your suggestion for creating a new contract per event sounds like the right approach (and what I had in mind as well). 

Since there is no need to maintain backward compatibility (this dApp still hasn't seen real-world usage), I think that while this isn't a trivial change, the lack of that constraint makes it substantially simpler to carry out. As you said, the main contract becomes a factory which generates event contracts, each with the existing logic and event ids become contract ids.

Another thing to consider it how to keep a mapping of existing events. On the one hand, we'll want to keep a mapping of each event owner to their event contracts so they could fetch them, but we will want to allow event-goers fetch all events they registered to.

Also, what are your thoughts concerning gas costs? Will it be substantially more expensive to create an event now (since each new event entails deploying a new contract to the network)? Or is it a relatively negligible difference?

Thank you for your work so far, it's great!

**Comment by dilatebrave** [comment]
@tomteman --- i'm thinking about things you mentioned and doing some testing about gas cost. I'll get back to you soon

**Comment by dilatebrave** [comment]
@tomteman @bakaoh --- Sorry for the delay, i was a bit busy lately. 

I've updated the EventStorage that deploy a new contract for each Event. EventStorage only store the array of Event address. That way, the gas cost will be:
- Deploy EventStorage: 1241234 vs 858349, increase 45%. This's one time fee so i think it's acceptable
- Create Event: 721141 vs 104975, increase 590%. That's a lot. I can move most of Event logic to EventStorage, just store the balance in the Event to make the Event contract deploy cheaper. But i want to isolate each event from others, so i choose that way.
- registerToEvent, checkin, charge: the gas cost almost the same.

About list events that user owns or attends, i've tried keep the map but that make the cost for register a lot higher, that cost add up for each attendee so i don't go that way. To get that list, i loop through the events list to check. Till don't know the scalability of this approach.

**Comment by bakaoh** [comment]
@tomteman -- the new contract is a lot different from the old one. so which contract should i continue #3 with?

**Comment by vs77bb** [comment]
Hi @tomteman any update on your side here?

**Review by tomteman — APPROVED** [review]

**Comment by tomteman** [comment]
@bakaoh @dilatebrave  sorry it took so long to merge your PR, the past two weeks have been pretty crazy. I sincerely apologize you had to wait so long, and I really hope it won't deter you from working with me again in the future, I assure you this isn't how I usually operate 😅

**Pull request closed without merging**
